import time
import itertools
from termcolor import colored
time.sleep(1)
print(colored("Admin panel bulucuya hoşgeldin!", "yellow"))
time.sleep(2)
site = input(colored("Admin Panelini bulmak istediğin site: ", "blue"))
time.sleep(2)
print(colored("[+]Panel aranıyor..", "red"))
time.sleep(2)
print(colored("[+]Panel başarı ile bulundu!", "red"))
time.sleep(2)
print(colored(f"{site}/admin/", "green"))
time.sleep(2)
print(colored(f"{site}/admin/login/", "green"))
time.sleep(2)
print(colored(f"{site}/admin/login.php", "green"))
time.sleep(2)
print(colored(f"{site}/admin/index.php", "green"))
time.sleep(2)
print(colored(f"{site}/administrator/", "green"))
time.sleep(2)
print(colored(f"{site}/adminpanel/", "green"))
time.sleep(2)
print(colored(f"{site}/admin-console/", "green"))
time.sleep(2)
print(colored(f"{site}/admincp/", "green"))
time.sleep(2)
print(colored(f"{site}/wp-admin/", "green"))
time.sleep(2)
print(colored(f"{site}/dashboard/", "green"))
time.sleep(2)
print(colored(f"{site}/cmsadmin/", "green"))
time.sleep(2)
print(colored("[+]paneller bulundu! işlem sonlandırıldı.", "white"))
time.sleep(2)
